### ISSUE TITLE
Problem after switching to Apollo GraphQL server express

### ISSUE THREAD

**Issue by poltak** [2fd/graphdoc#18] opened 2016-12-19 07:11 UTC
Previously was running my schema with [express-graphql](https://github.com/graphql/express-graphql) and graphdoc was working fine running against my dev GraphQL endpoint. Recently decided to switch to [graphql-server-express](https://github.com/apollostack/graphql-server) (Apollo server), and now the same graphdoc command results in: 
```
[405] Method Not Allowed on http://localhost:5000/graphql
```

Is this a known thing with Apollo server? 

It works if I manually generate a schema.json by querying IntrospectionQuery, then running graphdoc against that.

**Comment by 2fd** [comment] 2016-12-19 15:06
If the problem is that APOLLO server only supports POST requests.

https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L49

I will solve it for the next release.

Thanks.

**Comment by 2fd** [comment] 2017-02-28 10:34
Resolved in v2.0.0

**Closed by 2fd** 2017-02-28 10:34 UTC
Labels: bug
